events {
    worker_connections 1024;
}

http {
    upstream grpc_backend {
        least_conn;
        server server:50051;
    }

    server {
        listen 8080 http2;

        location / {
            grpc_pass grpc://grpc_backend;
        }
    }
}


